My contribution2
wasimreja/book-finder pull request #188
Opened 2022-10-15 08:02 UTC by Purva2803

### Description

(Write your answer here.)

### Checklist

- [ ] I am making a proper pull request, not spam.
- [ ] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)

## Add relevant screenshot or video (if any)

(Add here)

2022-10-15 09:58 UTC, wasimreja requested changes
make the necessary changes

2022-10-15 09:58 UTC, wasimreja commented on index.html
> +    Copyright © 2022 BookFinder
```suggestion
    Copyright © 2022 <a href="https://github.com/wasimreja/book-finder">BookFinder</a>

```

2022-10-15 09:58 UTC, wasimreja commented on index.html
> +    <div class="link"><a href="https://github.com/wasimreja/book-finder">Github</a></div>
```suggestion

```

2022-10-15 09:58 UTC, wasimreja commented on style.css
> +.link a{
```suggestion
.foot a:hover {
    color: #bfbfbf;
    text-decoration: none;
    transition: all 0.3s linear;


```

2022-10-17 13:27 UTC, Purva2803 commented
Yes i Worked on it just haven't created pull request will do by tonight.

2022-10-17 16:42 UTC, wasimreja reviewed
update your branch with the main project

2022-10-17 16:42 UTC, wasimreja commented on index.html
> +    <div class="link">
remove this
```suggestion


```

2022-10-17 16:42 UTC, wasimreja commented on index.html
> +    Made with ❤️ by <a href="https://github.com/wasimreja">Wasim Raja</a>
```suggestion
    Made with ❤️ by <a href="https://github.com/wasimreja">Wasim Reja</a>

```

2022-10-17 16:42 UTC, wasimreja commented on style.css
> +.c1{
remove this 
```suggestion
```

2022-10-17 16:42 UTC, wasimreja commented on style.css
> +.link a:hover{
remove this
```suggestion

```

2022-10-17 16:44 UTC, wasimreja commented on style.css
> +    transition: all 0.3s linear ;
remove this
```suggestion
```

2022-10-17 16:44 UTC, wasimreja commented on style.css
> +.link a{
remove this 
```suggestion
```

2022-10-17 19:03 UTC, wasimreja commented on style.css
> +	padding: 1rem 1rem;
```suggestion
	padding: 2rem 2rem;
```

2022-10-18 15:18 UTC, wasimreja commented
@Purva2803 resolve conflicts

2022-10-18 15:39 UTC, closed without merging

2022-10-18 17:21 UTC, Purva2803 commented
sorry @wasimreja for making you do this much efforts I am contributing for the first time so it's my learning phase there are the issues with branches so I am doing all the changes in the main and creating a pull request .