#250 Feature:implemented a footer
wasimreja/book-finder pull request #262
Opened 2023-02-15 17:45 UTC by shreyanka155

### Implemented a footer for creating social icons.

(Write your answer here.)

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

![Screenshot (6)](https://user-images.githubusercontent.com/101724719/219110222-0b53ecdc-02fb-40bd-b889-b8d59ce3a59c.png)

2023-02-15 19:41 UTC, wasimreja requested changes
Add hover to icons.

Twitter background color: #00aced
LinkedIn background color: #007bb6
Instagram background color: #ea2c59 

Add `transition: all .2s linear`

2023-02-15 19:41 UTC, wasimreja commented on style.css
> +  background-color:#403e3e;
```suggestion
  background-color: #33353d;
```

2023-02-15 19:41 UTC, wasimreja commented on style.css
> +  color:#737373;
```suggestion
  color: #818a91;
```

2023-02-16 06:00 UTC, shreyanka155 commented
Which width and height do i change....icons or background?

2023-02-16 06:10 UTC, shreyanka155 commented
Please review my code again i have updated the code using "amend" in the same commit.

2023-02-16 11:10 UTC, wasimreja commented
@shreyanka155 all good but the icons background color doesn't change on hover

2023-02-16 13:47 UTC, shreyanka155 commented
Will fix the issue within today .....

2023-02-16 14:57 UTC, shreyanka155 commented
Fixed the issue,please check again.Let me know if further changes required.

2023-02-17 10:22 UTC, wasimreja requested changes
remove padding instead add this
```
.icons i {
  width: 40px;
  height: 40px;
  line-height: 40px;
  margin-left: 6px;
  border-radius: 100%;
  background-color: #33353d;
  color: #818a91;
  display: inline-block;
  text-align: center;
  transition: all .2s linear;
```

add white color to icons on hover
```
.twitter :hover {
  background-color: #00aced;
  color: #fff;
}

.linkedin :hover{
  background-color: #007bb6;
  color: #fff;
}

.instagram :hover{
  background-color: #ea2c59;
  color: #fff;
}

2023-02-17 10:25 UTC, wasimreja commented on style.css
> +  color: #e3e2e9;
remove this
```suggestion
```

2023-02-17 13:59 UTC, shreyanka155 commented
Code updated and colour removed.Please check.

2023-02-17 16:16 UTC, merged