Jwoc
wasimreja/book-finder pull request #267
Opened 2023-02-16 10:08 UTC by realsh9dy

the footer was modified

2023-02-16 11:39 UTC, wasimreja requested changes
set a variable `--footer-color` in the root and dark theme. 
in root set the footer color to `#f4f1f1` and in dark theme `#26272b`

2023-02-16 11:39 UTC, wasimreja commented on index.html
> +      Made with ❤️ by <a href="https://github.com/wasimreja"><b>Wasim Reja</b></a>
keep it as is

```suggestion
      Made with ❤️ by <a href="https://github.com/wasimreja">Wasim Reja</a>

```

2023-02-16 11:39 UTC, wasimreja commented on style.css
> +	color: #27231F;
```suggestion
	color: #737373;
```

2023-02-16 12:11 UTC, realsh9dy commented on style.css
> +	color: #27231F;
the requested changes are made

2023-02-16 12:12 UTC, realsh9dy commented
Done.

2023-02-17 10:29 UTC, wasimreja commented on style.css
> +  background-color: #fca567;
```suggestion
  background-color: var(--footer-color);
```

2023-02-17 10:30 UTC, wasimreja reviewed
make all the necessary changes

2023-02-17 10:30 UTC, wasimreja commented on index.html
> +      Made with ❤️ by <a href="https://github.com/wasimreja"><b>Wasim Reja</b></a>
@realsh9dy

2023-02-17 10:30 UTC, wasimreja commented on style.css
> +	color: #27231F;
@realsh9dy

2023-02-17 10:44 UTC, realsh9dy commented
please check

2023-02-17 11:18 UTC, closed without merging