added pagination
wasimreja/book-finder pull request #310
Opened 2023-03-04 17:03 UTC by Awesomeasma

### Description

(Write your answer here.)

### Checklist

- [ ] I am making a proper pull request, not spam.
- [ ] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)

## Add relevant screenshot or video (if any)

(Add here)

2023-03-07 10:46 UTC, wasimreja requested changes
@Awesomeasma great work. it would be better if the pagination shows after you search for a book. and enhance pagination design.
https://codepen.io/MarioD/pen/OmWaqz

2023-03-07 10:51 UTC, vk20july commented
@wasimreja sir but this is unfair for me as you assigned this task to me and i have also made a PR for this

2023-03-07 16:19 UTC, Awesomeasma commented
@wasimreja 
I have updated it. Please review.

2023-03-08 16:33 UTC, wasimreja requested changes
@Awesomeasma pagination is not working and the button is overlapping. fix this. add padding to the bottom. 
![Screenshot 2023-03-08 at 21-48-35 Book Finder](https://user-images.githubusercontent.com/77227201/223769012-849a380c-ff9b-4765-ba6e-0b0fc001d23b.png)

2023-03-08 16:33 UTC, wasimreja commented on css/style.css
> +  background: #f6af54;
```suggestion
  background: #dbd3d3;
```

2023-03-08 16:33 UTC, wasimreja commented on css/style.css
> +  fill: #f6af54;
```suggestion
  fill: #dbd3d3;
```

2023-03-08 16:33 UTC, wasimreja commented on css/style.css
> +  opacity: 0.6;
```suggestion
  fill: #d0c5c5;
```

2023-03-08 17:56 UTC, wasimreja requested changes

2023-03-08 17:56 UTC, wasimreja commented on css/style.css
> +  background: #dc3545;
```suggestion
  background: #dbd3d3;
```

2023-03-08 17:56 UTC, wasimreja commented on css/style.css
> +  background: #dbd3d3;
```suggestion
  background: #eba544;
```

2023-03-09 06:23 UTC, Awesomeasma commented
> @Awesomeasma pagination is not working and the button is overlapping. fix this. add padding to the bottom. you have put .vscode file to css. delete this. ![Screenshot 2023-03-08 at 21-48-35 Book Finder](https://user-images.githubusercontent.com/77227201/223769012-849a380c-ff9b-4765-ba6e-0b0fc001d23b.png)

I apologize sir, I have updated the css & other components, I am fixing the functionality of the pagination buttons, I'll get it done, soon.

2023-03-09 11:43 UTC, Awesomeasma commented
> @Awesomeasma pagination is not working and the button is overlapping. fix this. add padding to the bottom. you have put .vscode file to css. delete this. ![Screenshot 2023-03-08 at 21-48-35 Book Finder](https://user-images.githubusercontent.com/77227201/223769012-849a380c-ff9b-4765-ba6e-0b0fc001d23b.png)

Please check once..

2023-03-09 12:28 UTC, wasimreja commented
@Awesomeasma fix the functionality of the pagination. your branch has conflicts. resolve this. rest is okay.

2023-03-09 12:39 UTC, Awesomeasma commented
> @Awesomeasma fix the functionality of the pagination. your branch has conflicts. resolve this. rest is okay.

Please tell me how do i fix it, I am trying to do so, but i am not able to.

2023-03-09 12:40 UTC, wasimreja commented
> > @Awesomeasma fix the functionality of the pagination. your branch has conflicts. resolve this. rest is okay.
> 
> Please tell me how do i fix it, I am trying to do so, but i am not able to.

dm me on discord.

2023-03-09 15:53 UTC, closed without merging