about us page updated
wasimreja/book-finder pull request #316
Opened 2023-03-07 05:11 UTC by khushimarothi

### Description

made the page responsive and updated it with some new things

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#315 

## Add relevant screenshot or video (if any)
![Screenshot (32)](https://user-images.githubusercontent.com/85816852/223325688-15d95b6d-a3ff-4962-bd63-406dccb52558.png)
![Screenshot (31)](https://user-images.githubusercontent.com/85816852/223325706-2a4fe56e-0b9e-462d-a5d4-c320d4a1bc59.png)
![Screenshot (34)](https://user-images.githubusercontent.com/85816852/223325726-33fb332c-b7a6-424c-92b6-ca595abc119c.png)
![Screenshot (33)](https://user-images.githubusercontent.com/85816852/223325733-9b370261-1336-45cf-a46d-3ba719875c63.png)

2023-03-07 10:32 UTC, wasimreja requested changes
beautiful work. some changes are required. 
- before perks section, keep everything as it was.
- remove free and customize how you read. instead you can add along with the books for reading, audio books are also available.
- increase the font size of perks.
```css
font-family: "Josefin Sans", sans-serif;
font-weight: 300;
```
- keep font family of benefit card text to comfortaa.
- keep font weight of card title to 600 and increase margin bottom.

2023-03-07 12:13 UTC, khushimarothi commented
Will do rest all the changes.. but I feel that animated about card was not looking good. That's why I just changed it

2023-03-07 14:12 UTC, wasimreja commented
> Will do rest all the changes.. but I feel that animated about card was not looking good. That's why I just changed it. Rest what ever you say. Just sharing my opinion

okay. remove the floating animation.

2023-03-07 14:14 UTC, wasimreja commented
@khushimarothi all right. remove the floating animation.

2023-03-07 14:50 UTC, khushimarothi commented
Please check now

2023-03-08 15:39 UTC, wasimreja commented on about.html
> +      <p>“Thanks to Book-Finder, there is no reason to buy books anymore.”<span class="s"> - User</span></p>
```suggestion
```
remove this.

2023-03-08 16:05 UTC, khushimarothi commented
You deleted the comment .. Should I delete that line. ?? if not then please merge don't keep it on waiting for so long

2023-03-08 16:10 UTC, wasimreja requested changes
- before perks section, no need to change anything. the illustration is becoming smaller.  
- add this to perks title.
```css
font-family: "Josefin Sans", sans-serif;
font-weight: 300;
```
- remove the last card and keep only 3 cards. keep the sequence as search in seconds, read anytime, anywhere and audio books respectively.

2023-03-08 16:35 UTC, merged