Faq
wasimreja/book-finder pull request #333
Opened 2023-03-12 16:19 UTC by S-ishita

### Description
Added faq page.

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

Closes #332 

## Add relevant screenshot or video (if any)

https://user-images.githubusercontent.com/104543751/224557830-f6f63160-a463-4d7a-9d83-5af949a53c72.mp4

2023-03-12 18:04 UTC, wasimreja requested changes
-  faq page navbar is not updated.
- change font family of container.
- change faq illustration to [this.](https://assets.materialup.com/uploads/ba8ec2f8-f51b-4ff3-9586-a2a8b2d353bc/preview.jpg)

2023-03-12 18:04 UTC, wasimreja commented on faq.html
> +                    <div class="answer">A: It helps you to read any time and anywhere.For more feature related information head to features page..
```suggestion
                    <div class="answer">A:  You can search books by title, author and ISBN number. For more feature related information head to features page.
```

2023-03-12 18:04 UTC, wasimreja commented on faq.html
> +                    <div class="question">Q:  Do I need any special software to use it?</div>
```suggestion
```

2023-03-12 18:04 UTC, wasimreja commented on faq.html
> +                    <div class="answer">A: Book Finder is a one stop solution for all kinds of book related searches making it preferable over other websites.
```suggestion
                    <div class="answer">A: Book Finder is open-source free search engine with over a million books making it preferable over other websites.
```

2023-03-12 18:08 UTC, S-ishita commented
> * faq page navbar is not updated.
> * change font family of container.
> * change faq illustration to [this.](https://assets.materialup.com/uploads/ba8ec2f8-f51b-4ff3-9586-a2a8b2d353bc/preview.jpg)
> * change color of `+` to `#eba544`

faq navbar is updated..please check again

2023-03-12 18:10 UTC, wasimreja commented
![Screenshot 2023-03-12 at 23-39-29 Book Finder](https://user-images.githubusercontent.com/77227201/224563936-68ff253c-5975-4b3d-8aa9-86a852fc1eff.png)
![Screenshot 2023-03-12 at 23-39-13 Book Finder](https://user-images.githubusercontent.com/77227201/224563942-cef5a43c-1337-49ca-9745-854297e29170.png)

2023-03-12 18:31 UTC, S-ishita commented
Done @wasimreja

2023-03-12 18:48 UTC, wasimreja commented
don't change other pages style. 
![Screenshot 2023-03-13 at 00-04-24 Book Finder](https://user-images.githubusercontent.com/77227201/224565524-bda60696-a139-4601-baa0-9ec403df8acb.png)
keep your nav like this just put faq before contact.
![Screenshot 2023-03-12 at 23-39-29 Book Finder](https://user-images.githubusercontent.com/77227201/224563936-68ff253c-5975-4b3d-8aa9-86a852fc1eff.png)
otherwise it will look like this.
![Screenshot 2023-03-13 at 00-14-08 Book Finder](https://user-images.githubusercontent.com/77227201/224565670-8c17761e-902c-4677-bb01-aa1434bb5fbb.png)
you haven't changed the description as said. and remove _Do I need any special software to use it?_
`+` is looking too small. previous one was okay. i have said to change the color.

2023-03-12 19:00 UTC, S-ishita commented
previous one was unicode its color cant be changed

2023-03-13 08:11 UTC, S-ishita commented
> previous '+' was unicode its color cant be changed

Can you please tell if i keep it unicode or make it color code one?

2023-03-13 08:17 UTC, wasimreja commented
keep it unicode and do the other changes

2023-03-13 09:28 UTC, closed without merging