add scroll to top button
wasimreja/book-finder pull request #92
Opened 2022-10-07 07:01 UTC by cu8code

### Description

added scroll to top button
#90

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#90 this fix was made according to this issue

## Add relevant screens

https://user-images.githubusercontent.com/109351887/194487306-23f9dc4a-e21a-4221-82dc-31b2706d5768.mp4

2022-10-07 13:49 UTC, cu8code commented
Hey, I also added the fade in and fade out effect

https://user-images.githubusercontent.com/109351887/194569063-09f3b687-a4e6-4df1-8ecb-1dcef15ab21c.mp4

2022-10-08 08:40 UTC, wasimreja requested changes
resolve the conflict

2022-10-08 08:42 UTC, wasimreja commented on style.css
> +	background: rgb(73, 122, 255);
change background to rgb(208, 197, 197)

2022-10-08 08:42 UTC, wasimreja commented on index.html
> +    <i class="fa fa-arrow-up" />
remove this code

2022-10-08 08:45 UTC, wasimreja commented on index.html
> +    <i class="fa fa-arrow-up" />
remove this code

2022-10-08 15:28 UTC, cu8code commented
@wasimreja I made the required changes 🙂

2022-10-08 15:44 UTC, merged